spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: spring
        url: jdbc:mysql://localhost:3306/usersDB?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
